### ISSUE TITLE
Peer Feedback  from Group 9

### ISSUE THREAD

**Issue by yuyanguo** [UBC-MDS/happy-dash#29]
Hello group 10,

Great Job! We (Jacob, Santiago, Yuyan from group 9) all enjoy reviewing your World Happiness Report Explorer app. It is very organized and informative. If I were a policy analyst working for the government, I will find the app is super useful for helping me identify how happiness scores change over time for our country while comparing with the rest of the world. If I saw a country had a much better performance than our county, I can even explore which factors make such difference(e.g. GDP, family, life expectancy). In this way, I think it can point me to right direction for my further research and even future advocacy.

**What we like:**

-  As I mentioned, we like the overall layout of your app. Everything is so clear and organized. The structure of the dashboard allow us to easily and quickly understand the app.
-  We also like the way that the drop-downs and sliders interact with the plots. As I select more features, more plots will show up! So cool!
- The overall plot types are very efficient! We can always easily compare the happiness score over time for two countries. The line plots are very suitable and in line with the purpose of the app.
- The app takes just one screen, we like it as there is no scrolling needed. 

**What we suggest:** (we might be wrong)

- We found that there are so many options in the countries, we like it. But we would suggest to add another filter, such as continent. For the purpose of this dashboard, if I really want to compare one county with some other countries together(as benchmark), then I cannot do that. All I can do is select them one by one and then drop them one by one. Also I select more than 5 countries, the app becomes overwhelming quickly.
-  We also noticed that for the contribution plots, there is no y-axis scales for the plots on the right hand side. Initially, I assume they have the same scale as the plots on the left. But after careful comparison, I do not think this is how it works, at least from an audience perspective. Because the white grid lines are not aligned. Maybe it worth to add the scales of the y-axis for all plots to avoid confusion.
- I am using the mac laptop with full screen. I found out that if I select all the contribution plots, the titles and the axes of those plots will all overlap together. Maybe it's because there are so many plots on the same screen. Maybe try to combine two relatively unimportant factor together.
-  Maybe add a card or some other plot types in the app. Currently they are all line charts.(But still very clear!)

Overall, we think your group did a amazing job in designing the dashboard! Hope our suggestions can help in your Milestone4. Have a great weekend!

**Comment by dbandrews** [comment]
Thanks Group 9!

We have addressed this feedback in #34, #30
